//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserList1
    {
        public int Id { get; set; }
        public string NombreDonante { get; set; }
        public string Departamento { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> DUI { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string GrupoSanguineo { get; set; }
        public string FechaDonacion { get; set; }
        public string Correo { get; set; }
        public string estatus { get; set; }
    }
}
